# Generated by Django 5.2.8 on 2025-11-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.CharField(default='Ziyad', max_length=256),
            preserve_default=False,
        ),
    ]
